DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  userName VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE messages (
id SERIAL PRIMARY KEY NOT NULL,
sender_email VARCHAR(255) NOT NULL,
sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
content TEXT
)